# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "OneTool"

# The default layout to use for your application (located in
# views/layouts/page.tt)
layout: "page"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

engines:
   template_toolkit:
      PLUGIN_BASE: 'OneTool::Web::Template::Plugin'
      start_tag: '[%'
      stop_tag: '%]' 
